name: CI-Model-multiplexing-serve-app
on:
  push:
    branches:
      - ENH/1/serve-model-multiplexing-code
      - main
jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
      - name: Set file name
        run: echo "FILE_NAME=model-multiplex-app-v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Create directory and copy files
        run: |
          mkdir -p "$FILE_NAME"
          if [ -f model_multiplexing_app.py ]; then
            cp model_multiplexing_app.py "$FILE_NAME"
          else
            echo "Error: model_multiplexing_app.py not found!" >&2
            exit 1
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE_NAME }}
          path: ./${{ env.FILE_NAME }}
