name: CI-CD-Pipeline-Model-Multiplexing-Serve-App

on:
  push:
    branches:
      - ENH/1/serve-model-multiplexing-code
      - main

env:
  RELEASE_TAG: v${{ github.run_number }}_${{github.sha}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # TIMESTAMP: ${{ github.event.head_commit.timestamp}}
  ASSET_URL: https://github.com/${{ github.repository }}/archive/refs/tags/v${{ github.run_number }}_${{ github.sha }}.zip

jobs:
  Build-Serve-App:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest code
        uses: actions/checkout@v4
      
      - name: Check RELEASE_TAG and ASSET_URL
        run: |
          echo ${{env.RELEASE_TAG }}
          echo ${{env.ASSET_URL}}
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Prepare Serve Build Config
        run: |
          sh ./scripts/check_build_files.sh
      
      # Run the python code to format the build and deploy yaml files
      - name: Prepare Deploy Config
        run: |
          python format_yaml.py -b manifests/app-build-config.yaml -d manifests/app-deploy-config.yaml -o manifests/app-deploy-config.yaml -w ${{env.ASSET_URL}}
          tree manifests

      - name: Create folder structure for artifacts
        run: |
          mkdir -p ${{ env.RELEASE_TAG}}
          mkdir -p ${{ env.RELEASE_TAG}}/manifests
          cp -r manifests/app-build-config.yaml ${{ env.RELEASE_TAG}}/manifests/app-build-config.yaml
          cp -r manifests/app-deploy-config.yaml ${{ env.RELEASE_TAG}}/manifests/app-deploy-config.yaml
          cp -r app/*app.py ${{ env.RELEASE_TAG}}/
          cp -r *.md ${{ env.RELEASE_TAG}}/
          tree ${{ env.RELEASE_TAG}}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RELEASE_TAG }}
          path: ./${{ env.RELEASE_TAG }}
          retention-days: 15

  Download-artifact-and-push-release:
    runs-on: ubuntu-latest
    needs: Build-Serve-App
    outputs:
      zip_url: ${{ steps.get_asset_url.outputs.ZIP_URL }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.RELEASE_TAG}}
      
      - name: List files
        run: |
          tree .
      
      - name: Publish artifact as Github release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: "${{ env.RELEASE_TAG }}"
          body_path: "./README.md"
      
      - name: Get ZIP file asset URL
        id: get_asset_url
        run: |
          echo ${{env.ASSET_URL}}
